backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "navigation"
    label: "Навігація"
    folder: "docs/navigation"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Тіло сторінки", name: "body", widget: "markdown" }

  - name: "features"
    label: "Функції J3M Sequencer"
    folder: "docs/features"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Тіло сторінки", name: "body", widget: "markdown" }

  - name: "faq"
    label: "FAQ"
    folder: "docs/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Тіло сторінки", name: "body", widget: "markdown" }
